# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f6517ed7d7e8b2101b49552c74a463bb5164d551290555e1b1ccd1b27a3322efdcd0916286746881e9cc41e785fc1c9cde51aa723aec3205a4487d1dca919c

test:
  secret_key_base: 67368867fb36d416070d195669e697919d7765ca751db2c7cafd389f607ce896d25acb6d4e1db9129461b115b61f959aaec898a7e536297467532dac17e9f0d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
